libc2dcolorconvert: fix arithmetic on a pointer to void
Use char* instead of void* for this
pointer arithmetic. Fixes the following:

hardware/qcom/media/libc2dcolorconvert/C2DColorConverter.cpp:321:70: error: arithmetic on a pointer to void
        srcSurfaceDef->phys0  = getMappedGPUAddr(fd, data, mSrcSize) + ((uint8_t *)data - (uint8_t *)base);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
hardware/qcom/media/libc2dcolorconvert/C2DColorConverter.cpp:333:70: error: arithmetic on a pointer to void
        dstSurfaceDef->phys0  = getMappedGPUAddr(fd, data, mDstSize) + ((uint8_t *)data - (uint8_t *)base);
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

Change-Id: Ia3d17a9e47811da118abc7802e64adc1d5c0cddf