mm-video: vidc: Get rid of OMX_VIDEO_PATH in make files
OMX_VIDEO_PATH is only defined at the top level makefile in
hardware/qcom/media/mm-video-v4l2.  As a result, if you run 'mm' at the
lower levels (i.e. in src/) the compilation fails, because the top level
makefile is never executed and OMX_VIDEO_PATH := "" in the lower level
makefile.  Hence, some header files are never found, e.g.:

hardware/qcom/media/mm-video-v4l2/vidc/vdec/inc/omx_vdec.h:103:32: fatal
error: extra_data_handler.h: No such file or directory

So just get rid of OMX_VIDEO_PATH and directly refer to the folders.

Change-Id: I195994b2f3d07b975b1612f58fa3e80af70e3e93